#!/bin/bash
#: Title        : file
#: Date         : 2021-09-07
#: Author       : "Oliver Santos Code"
#: Version      : 1.0
#: Description  : create FILENAME
#: Options      : None

printf "Hello" > FILENAME