#!/bin/bash
#: Title        : helloworld
#: Date         : 2021-08-17
#: Author       : "Oliver Santos Code" <@oliversantoscode>
#: Descriptions : print Hello, World!
#: Options      : None

printf "%s\n" "Hello, World!"
printf "%s\n" Hello, World!