#!/bin/bash
#: Title        : hexadecimal
#: Date         : 2021-08-24
#: Author       : "Oliver Santos Code" <@oliversantoscode>
#: Version      : 1.0
#: Description  : print hexadecimal color
#: Options      : None

printf "color: #%02x%02x%02x;\n" 15 155 255