#!/bin/bash
#: Title        : number
#: Date         : 2021-08-19
#: Author       : "Oliver Santos Code" <@oliversantoscode>
#: Version      : 1.0
#: Description  : print Number decimal and no greater than 10
#: Options      : None

printf "%d\n" 2021 19 45 56 0xff 011
printf "Enter a number between 10 and 20 inclusive: "
read number
if [ "$number" -lt 10 ]
then
    printf "%d is too low\n" "$number" >&2
    exit 1
elif [ "$number" -gt 20 ]
then
    printf "%d is too hight\n" "$number" >&2
    exit 1
else
    printf "You entered %d\n" "$number"
fi