#!/bin/bash
#: Title        : pipeline
#: Date         : 2021-09-15
#: Author       : "Oliver Santos Code" <@oliversantoscode>
#: Version      : 1.0
#: Description  : print RANDOM | FILENAME
#: Options      : None

printf "%s\n" "$RANDOM" "$RANDOM" "$RANDOM" "$RANDOM" | tee FILENAME
cat FILENAME